#!/bin/bash
# Wait for tiller to be available
until helm --kubeconfig=/etc/kubernetes/admin.conf list
do
    printf "." && sleep 1
done

# Clone the config repo (we should perhaps split this up into multiple repos, one for each setup).
git clone http://github.com/hashicorp/da-instruqt-security /tmp/security

# Run emojify app
kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f  /tmp/security/exercises/01-setup-consul/files/app

# Set workdir
set-workdir "/tmp/security/exercises/01-setup-consul/files/consul-helm"