#!/bin/bash
# Wait for tiller to be available
until helm --kubeconfig=/etc/kubernetes/admin.conf list
do
    printf "." && sleep 1
done

# Clone the config repo (we should perhaps split this up into multiple repos, one for each setup).
git clone https://github.com/hashicorp/service-mesh-training.git /tmp/service-mesh

# Install consul by running helm chart
helm --kubeconfig=/etc/kubernetes/admin.conf install -f /tmp/service-mesh/exercises/lab-01/02-install-consul/files/values.yaml /tmp/service-mesh/exercises/lab-01/02-install-consul/files/consul

# Run emojify app
kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f /tmp/service-mesh/exercises/lab-01/03-install-emojify-app/files/app

# Run prometheus + grafana
kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f /tmp/service-mesh/exercises/lab-01/04-install-prometheus-and-grafana/files/metrics-server
kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f /tmp/service-mesh/exercises/lab-01/04-install-prometheus-and-grafana/files/prometheus