---                                                    
apiVersion: apps/v1                                    
kind: Deployment
metadata:
  name: emojify-facedetect
  labels:
    app: emojify-facedetect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emojify-facedetect
  template:
    metadata:
      labels:
        app: emojify-facedetect
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
    spec:
      containers:
      - name: emojify-facedetect
        image: "nicholasjackson/emojify-facedetection:v0.1.2"
        env:
        - name: STATSD_ADDRESS
          value: localhost:9125
        ports:
        - containerPort: 9090
